groups = {
    mine = { deposits = 2 }
}

1 = {
    cost = 10
    modules = {
        mill = { economy = 1 stability = 1 }
        mine = { economy = 2 }
    }
}

2 = {
    cost = 20
    modules = {
        mill = { economy = 2 stability = 2 }
        mine = { economy = 4 }
    }
}

3 = {
    cost = 40
    slots = 2
    modules = {
        mill = { economy = 4 stability = 2 supply = 1 }
        mine = { economy = 6 supply = 1 }
    }
}

4 = {
    cost = 60
    slots = 2
    modules = {
        mill = { economy = 4 stability = 4 supply = 2 }
        mine = { economy = 8 supply = 2 }
    }
}

5 = {
    cost = 80
    slots = 4
    modules = {
        mill = { economy = 6 stability = 4 supply = 4 }
        mine = { economy = 8 loyalty = 2 supply = 4 }
    }
}

